{{- $fullName := include "files.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "files.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10G
spec:
  tls:
    - hosts:
        - files.ssp.{{ .Values.platform.domain }}
      secretName: {{ $fullName }}-tls
  rules:
    - host: files.ssp.{{ .Values.platform.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
