apiVersion: v1
kind: Service
metadata:
  name: {{ include "files.fullname" . }}
  labels:
{{ include "files.labels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "files.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
