apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "files.fullname" . }}
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: default
