apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "files.fullname" . }}
  labels:
{{ include "files.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "files.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "files.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - image: bytemark/webdav
          name: webdav
          env:
            - name: AUTH_TYPE
              value: "Basic"
            - name: USERNAME
              value: "admin"
            - name: PASSWORD
              value: {{ .Values.platform.admin.password }}
          volumeMounts:
            - mountPath: /var/lib/dav
              name: storage
              subPath: files-webdav
          ports:
            - name: http
              containerPort: 80
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "files.fullname" . }}
