- hosts: gluster
  become: yes
  tasks:
    - name: install GPG
      apt:
        name: gnupg
        state: present

    - name: Add an Apt signing key, will not download if present
      apt_key:
        url: https://download.gluster.org/pub/gluster/glusterfs/6/rsa.pub
        state: present
    
    - name: Add the Gluster Apt repository
      apt_repository:
        repo: 'ppa:gluster/glusterfs-6'

    - name: Install GlusterFS server
      apt:
        name: glusterfs-server
        state: present
        update_cache: true

    - name: Install GlusterFS client
      apt:
        name: glusterfs-client
        state: present
        update_cache: true

- hosts: gluster1
  become: yes
  tasks:
    - name: Introduce the other cluster nodes
      command: gluster peer probe {{ item }}
      with_items: "{{ groups.gluster }}"
