- hosts: host
  become: yes
  tasks:
  - name: Deny incoming traffic by default
    ufw:
      default: deny
      direction: incoming

  - name: Allow incoming SSH traffic
    ufw:
      rule: allow
      proto: tcp
      port: '22'

  - name: Enable UFW firewall settings
    ufw:
      state: enabled

  - name: Install necessary packages
    apt:
      name: xfsprogs,qemu-kvm,libvirt-clients,libvirt-daemon-system,bridge-utils,virt-manager,sysstat,apt-transport-https,ca-certificates,curl,software-properties-common,python-lxml
      state: present
      update_cache: true

  - name: Create the directory for the default storage pool
    file:
      path: /vmpool
      state: directory
      mode: 0755

  - name: Create the default storage pool
    virt_pool:
      command: define
      name: default
      xml: |
        <pool type='dir'>
          <name>default</name>
          <target>
            <path>/vmpool</path>
          </target>
        </pool>

  - name: Build the default storage pool
    virt_pool:
      command: build
      name: default

  - name: Enable the default storage pool
    virt_pool:
      name: default
      state: active

  - name: Enable autostart for default storage pool
    virt_pool:
      name: default
      autostart: yes

  - name: Create the directory for data pool 1
    file:
      path: /data1
      state: directory
      mode: 0755

  - name: Create data pool 1
    virt_pool:
      command: define
      name: data1
      xml: |
        <pool type='dir'>
          <name>data1</name>
          <target>
            <path>/data1</path>
          </target>
        </pool>

  - name: Build data pool 1
    virt_pool:
      command: build
      name: data1

  - name: Enable data pool 1
    virt_pool:
      name: data1
      state: active

  - name: Enable autostart for data pool 1
    virt_pool:
      name: data1
      autostart: yes

  - name: Create the directory for data pool 2 
    file:
      path: /data2
      state: directory
      mode: 0755

  - name: Create data pool 2
    virt_pool:
      command: define
      name: data2
      xml: |
        <pool type='dir'>
          <name>data2</name>
          <target>
            <path>/data2</path>
          </target>
        </pool>

  - name: Build data pool 2
    virt_pool:
      command: build
      name: data2

  - name: Enable data pool 2
    virt_pool:
      name: data2
      state: active

  - name: Enable autostart for for data pool 2
    virt_pool:
      name: data2
      autostart: yes
