platform:

  assets:
    kubernetes:
      version: 1.15.2-00

  # Your domain, the platform should be reachable through
  domain: example.com

  # The default Email address to be used by the platform
  email: support@example.com

  # The default administration user account
  admin:
    password: pw%ssp

  # The worker nodes configuration
  workers:
    ram: 4096

  # The storage settings
  storage:
    data:
      size: 300G

  # The network settings
  network:
    ipprefix: 10.99.99

  # The backup configuration
  backup:
    restic:
      url: http://restic-rest-server-url

custom:

  # Custom Kubernetes namespaces to be created upon installation 
  namespaces:
    # - name: my-namespace1
    # - name: my-namespace2
