platform:

  assets:
    kubernetes:
      version: 1.15.2-00
    calico:
      version: 3.11
    istio:
      version: 1.3.5
    nginx:
      version: 0.26.1
    certmanager:
      version: 0.12.0
    heketi:
      version: 9.0.0
    glusterfs:
      version: 6
    stash:
      version: 0.9.0-rc.2
    stashcli:
      version: 0.2.0

  # Your domain, the platform should be reachable through
  domain: example.com

  # The default Email address to be used by the platform
  email: support@example.com

  # The default administration user account
  admin:
    password: pw%ssp

  # The worker nodes configuration
  workers:
    ram: 4096

  # The storage settings
  storage:
    data:
      size: 300G

  # The network settings
  network:
    ipprefix: 10.99.99

  # The backup configuration
  backup:
    encryptionkey: tobechanged
    s3:
      access_key: <enter_aws_access_key_here>
      secret_key: <enter_aws_secret_key_here>
    restic:
      url: http://restic-rest-server-url

custom:

  # Custom Kubernetes namespaces to be created upon installation 
  namespaces:
    # - name: my-namespace1
    # - name: my-namespace2
