apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs.fullname" . }}
  labels:
{{ include "nfs.labels" . | indent 4 }}
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app.kubernetes.io/name: {{ include "nfs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
