apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: trayla
  name: bookstack-p
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: default
