apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-static
subsets:
  - addresses:
      - ip: 10.88.20.110
    ports:
      - port: 1
  - addresses:
      - ip: 10.88.20.111
    ports:
      - port: 1
  - addresses:
      - ip: 10.88.20.112
    ports:
      - port: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gluster
spec:
  ports:
  - port: 1
