apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 labels:
   name: letsencrypt-staging
 name: letsencrypt-staging
spec:
 acme:
   email: support@trayla.com
   http01: {}
   privateKeySecretRef:
     name: clusterissuer-letsencrypt-staging
   server: https://acme-staging-v02.api.letsencrypt.org/directory
