apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  labels:
{{ include "nfs.labels" . | indent 4 }}
spec:
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: default
