- hosts: host
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  become: yes
  tasks:

    # Enable the host firewall
  
    - name: Deny incoming traffic by default
      ufw:
        default: deny
        direction: incoming

    - name: Allow incoming SSH traffic
      ufw:
        rule: allow
        proto: tcp
        port: '22'

    - name: Enable UFW firewall settings
      ufw:
        state: enabled

    # Install neceassry software

    - name: Install necessary packages
      apt:
        name: qemu-kvm,libvirt-clients,libvirt-daemon-system,bridge-utils,virt-manager,libguestfs-tools,virt-top,sysstat,apt-transport-https,ca-certificates,curl,software-properties-common,python-lxml,python3-lxml,python-libvirt,python3-libvirt,python-pip
        state: present
        update_cache: true

    # Create the storage pools

    - name: Create the directory for the default storage pool
      file:
        path: /vmpool
        state: directory
        mode: 0755

    - name: Create the default storage pool
      virt_pool:
        command: define
        name: ssp_default
        xml: |
          <pool type='dir'>
            <name>ssp_default</name>
            <target>
              <path>/vmpool</path>
            </target>
          </pool>

    - name: Build the default storage pool
      virt_pool:
        command: build
        name: ssp_default

    - name: Enable the default storage pool
      virt_pool:
        name: ssp_default
        state: active

    - name: Enable autostart for default storage pool
      virt_pool:
        name: ssp_default
        autostart: yes

    - name: Create the directory for data pool 1
      file:
        path: /data/data1
        state: directory
        mode: 0755

    - name: Create data pool 1
      virt_pool:
        command: define
        name: ssp_data1
        xml: |
          <pool type='dir'>
            <name>ssp_data1</name>
            <target>
              <path>/data/data1</path>
            </target>
          </pool>

    - name: Build data pool 1
      virt_pool:
        command: build
        name: ssp_data1

    - name: Enable data pool 1
      virt_pool:
        name: ssp_data1
        state: active

    - name: Enable autostart for data pool 1
      virt_pool:
        name: ssp_data1
        autostart: yes

    - name: Create the directory for data pool 2 
      file:
        path: /data/data2
        state: directory
        mode: 0755

    - name: Create data pool 2
      virt_pool:
        command: define
        name: ssp_data2
        xml: |
          <pool type='dir'>
            <name>ssp_data2</name>
            <target>
              <path>/data/data2</path>
            </target>
          </pool>

    - name: Build data pool 2
      virt_pool:
        command: build
        name: ssp_data2

    - name: Enable data pool 2
      virt_pool:
        name: ssp_data2
        state: active

    - name: Enable autostart for data pool 2
      virt_pool:
        name: ssp_data2
        autostart: yes

    # Create the virtual network

    - name: Define the default network configuration
      virt_net:
        command: define
        name: ssp_default
        xml: |
          <network>
            <name>ssp_default</name>
            <forward mode='nat'>
              <nat>
                <port start='1024' end='65535'/>
              </nat>
            </forward>
            <bridge name='virbr0' stp='on' delay='0'/>
            <ip address='{{ platform.network.ipprefix }}.1' netmask='255.255.255.0'>
              <dhcp>
                <range start='{{ platform.network.ipprefix }}.230' end='{{ platform.network.ipprefix }}.245'/>
              </dhcp>
            </ip>
          </network>

    - name: Start the default network
      virt_net:
        command: start
        name: ssp_default

    - name: Set the default network to be auto started
      virt_net:
        autostart: yes
        name: ssp_default

    # Enable the system start procedure

    - name: Register the system startup procedure
      lineinfile:
        path: /etc/rc.local
        line: 'ansible-playbook -i /opt/mgmt/ssp/python/get-ansible-inventory.py /opt/mgmt/ssp/ansible/startup.yaml'
        create: yes
        mode: '0755'
