- hosts: host
  become: yes
  tasks:
  - name: Deny incoming traffic by default
    ufw:
      default: deny
      direction: incoming

  - name: Allow incoming SSH traffic
    ufw:
      rule: allow
      proto: tcp
      port: '22'

  - name: Enable UFW firewall settings
    ufw:
      state: enabled

  - name: Install necessary packages
    apt:
      name: xfsprogs,qemu-kvm,libvirt-clients,libvirt-daemon-system,bridge-utils,virt-manager,libguestfs-tools,virt-top,sysstat,apt-transport-https,ca-certificates,curl,software-properties-common,python-lxml,python-pip
      state: present
      update_cache: true

  - name: Create the directory for the default storage pool
    file:
      path: /vmpool
      state: directory
      mode: 0755

  - name: Create the default storage pool
    virt_pool:
      command: define
      name: default
      xml: |
        <pool type='dir'>
          <name>default</name>
          <target>
            <path>/vmpool</path>
          </target>
        </pool>

  - name: Build the default storage pool
    virt_pool:
      command: build
      name: default

  - name: Enable the default storage pool
    virt_pool:
      name: default
      state: active

  - name: Enable autostart for default storage pool
    virt_pool:
      name: default
      autostart: yes

  - name: Create the directory for data pool 1
    file:
      path: /data1
      state: directory
      mode: 0755

  - name: Create data pool 1
    virt_pool:
      command: define
      name: data1
      xml: |
        <pool type='dir'>
          <name>data1</name>
          <target>
            <path>/data1</path>
          </target>
        </pool>

  - name: Build data pool 1
    virt_pool:
      command: build
      name: data1

  - name: Enable data pool 1
    virt_pool:
      name: data1
      state: active

  - name: Enable autostart for data pool 1
    virt_pool:
      name: data1
      autostart: yes

  - name: Create the directory for data pool 2 
    file:
      path: /data2
      state: directory
      mode: 0755

  - name: Create data pool 2
    virt_pool:
      command: define
      name: data2
      xml: |
        <pool type='dir'>
          <name>data2</name>
          <target>
            <path>/data2</path>
          </target>
        </pool>

  - name: Build data pool 2
    virt_pool:
      command: build
      name: data2

  - name: Enable data pool 2
    virt_pool:
      name: data2
      state: active

  - name: Enable autostart for for data pool 2
    virt_pool:
      name: data2
      autostart: yes

  - name: Destroy the default network configuration
    virt_net:
      command: destroy
      name: default 

  - name: Remove the default network configuration
    virt_net:
      command: undefine
      name: default

  - name: Define the default network configuration
    virt_net:
      command: define
      name: default
      xml: |
        <network>
          <name>default</name>
          <forward mode='nat'>
            <nat>
              <port start='1024' end='65535'/>
            </nat>
          </forward>
          <bridge name='virbr0' stp='on' delay='0'/>
          <ip address='10.88.20.1' netmask='255.255.255.0'>
            <dhcp>
              <range start='10.88.20.230' end='10.88.20.245'/>
            </dhcp>
          </ip>
        </network>

  - name: Start the default network
    virt_net:
      command: start
      name: default

  - name: Set the default network to be auto started
    virt_net:
      autostart: yes
      name: default

  - name: Register the system startup procedure
    lineinfile:
      path: /etc/rc.local
      line: 'ansible-playbook -i /opt/mgmt/ssp/ansible/inventory.yaml /opt/mgmt/ssp/ansible/startup.yaml'
      create: yes
      mode: '0755'
