- hosts: host
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

  # Wait some time to let the KVM service be started
  - pause:
      seconds: 30

  # Start all virtual machines
  - name: Starting virtual machines
    shell: '/usr/bin/virsh -c qemu:///system start ssp_{{ item }}'
    with_items: "{{ groups.vms }}"

  # Wait some time to let the KVM service be started
  - pause:
      seconds: 30

- hosts: console
  become: yes
  vars_files:
    - /opt/mgmt/values-ssp.yaml
  tasks:

  # Wait for the Kubernetes cluster to come up
  - name: Wait for the Kubernetes cluster to come up
    shell: kubectl cluster-info
    register: result
    until: result.stdout.find("running") != -1
    retries: 50
    delay: 10

# Include host firewall settings
- name: Include the host firewall settings
  import_playbook: host-firewall.yaml

# Include Kubernetes firewall settings
- name: Include the Kubernetes firewall settings
  import_playbook: kubernetes-firewall.yaml
