apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ssp-base
  name: dockerreg-p
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: default
