apiVersion: v1
kind: Service
metadata:
  namespace: ssp-base
  name: dockerreg-p
  labels:
    app: dockerreg
    env: p
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
  selector:
    app: dockerreg
    env: p
