apiVersion: v1
kind: Service
metadata:
  name: dockerreg
  labels:
    app: dockerreg
    env: p
spec:
  type: NodePort
  clusterIP: 10.96.10.1
  ports:
  - name: http
    port: 5000
  selector:
    app: dockerreg
    env: p
